server:
  port: 8080

  tomcat:
    uri-encoding: utf-8
    accept-count: 1000
    max-connections: 2000
    threads:
      max: 200
      min-spare: 100

management:
  endpoints:
    web:
      exposure:
        include: "*"  # 或者指定需要暴露的端点，如 "health,info"
      base-path: /actuator  # 暴露端点的基础路径，默认为 "/actuator"
    shutdown:
      enabled: true  # 是否启用 shutdown 端点，默认为 true


